# Generated by Django 5.0.6 on 2024-06-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
    ]
