# Generated by Django 5.0.6 on 2024-06-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_usuario_apellido_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('activo', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='pagina.categoria')),
            ],
            options={
                'ordering': ['id_producto'],
            },
        ),
    ]
