# Generated by Django 5.0.6 on 2024-06-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_producto_foto_alter_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
